export enum RegionEnum {
    Beja = 'Béja',
    BenArous = 'Ben_Arous',
    Bizerte = 'Bizerte',
    Gabes = 'Gabés',
    Gafsa = 'Gafsa',
    Jendouba = 'Jendouba',
    Kairouan = 'Kairaouan',
    Kasserine = 'Kasserine',
    Kebili = 'Kébili',
    Kef = 'Le kef',
    Mahdia = 'Mahdia',
    Manouba = 'La manouba',
    Medenine = 'Médenine',
    Monastir = 'Monastir',
    Nabeul = 'Nabeul',
    Sfax = 'Sfax',
    SidiBouzid = 'Sidi Bouzid',
    Siliana = 'Siliana',
    Sousse = 'Sousse',
    Tataouine = 'Tataouine',
    Tozeur = 'Tozeur',
    Tunis = 'Tunis',
    Zaghouan = 'Zaghouan',
    Ariana = 'Ariana'
  }